// BBVA Brand Color Palette

export const COLORS = {
  // Brand
  primary: '#003366',       // BBVA Dark Blue
  secondary: '#00A8E8',     // BBVA Light Blue

  // Neutrals
  white: '#FFFFFF',
  black: '#000000',
  gray100: '#F5F5F5',
  gray200: '#EEEEEE',
  gray300: '#E0E0E0',
  gray400: '#BDBDBD',
  gray500: '#9E9E9E',
  gray600: '#757575',
  gray700: '#616161',
  gray800: '#424242',
  gray900: '#212121',

  // Semantic
  success: '#4CAF50',
  error: '#F44336',
  warning: '#FF9800',
  info: '#2196F3',

  // Utility
  transparent: 'transparent',
  overlay: 'rgba(0,0,0,0.5)',
} as const;

export type ColorKey = keyof typeof COLORS;

export const LIGHT_THEME_COLORS = {
  background: COLORS.gray100,
  surface: COLORS.white,
  surfaceVariant: COLORS.gray200,
  primary: COLORS.primary,
  primaryVariant: '#004E99',
  secondary: COLORS.secondary,
  secondaryVariant: '#0089BF',
  text: COLORS.gray900,
  textSecondary: COLORS.gray600,
  textDisabled: COLORS.gray400,
  textInverse: COLORS.white,
  border: COLORS.gray300,
  borderFocus: COLORS.secondary,
  icon: COLORS.gray700,
  iconInverse: COLORS.white,
  placeholder: COLORS.gray500,
  divider: COLORS.gray200,
  card: COLORS.white,
  cardBorder: COLORS.gray300,
  header: COLORS.primary,
  headerText: COLORS.white,
  tabBar: COLORS.white,
  tabBarActive: COLORS.primary,
  tabBarInactive: COLORS.gray500,
  inputBackground: COLORS.white,
  inputBorder: COLORS.gray400,
  buttonPrimary: COLORS.primary,
  buttonPrimaryText: COLORS.white,
  buttonSecondary: COLORS.secondary,
  buttonSecondaryText: COLORS.white,
  buttonOutlineBorder: COLORS.primary,
  buttonOutlineText: COLORS.primary,
  buttonDisabled: COLORS.gray300,
  buttonDisabledText: COLORS.gray500,
  success: COLORS.success,
  error: COLORS.error,
  warning: COLORS.warning,
  info: COLORS.info,
  successBackground: '#E8F5E9',
  errorBackground: '#FFEBEE',
  warningBackground: '#FFF3E0',
  infoBackground: '#E3F2FD',
  overlay: COLORS.overlay,
  shimmer: COLORS.gray200,
  shimmerHighlight: COLORS.gray100,
} as const;

export const DARK_THEME_COLORS = {
  background: COLORS.gray900,
  surface: COLORS.gray800,
  surfaceVariant: COLORS.gray700,
  primary: COLORS.secondary,
  primaryVariant: '#33BBED',
  secondary: COLORS.primary,
  secondaryVariant: '#004E99',
  text: COLORS.white,
  textSecondary: COLORS.gray400,
  textDisabled: COLORS.gray600,
  textInverse: COLORS.gray900,
  border: COLORS.gray700,
  borderFocus: COLORS.secondary,
  icon: COLORS.gray400,
  iconInverse: COLORS.gray900,
  placeholder: COLORS.gray600,
  divider: COLORS.gray700,
  card: COLORS.gray800,
  cardBorder: COLORS.gray700,
  header: COLORS.gray800,
  headerText: COLORS.white,
  tabBar: COLORS.gray800,
  tabBarActive: COLORS.secondary,
  tabBarInactive: COLORS.gray600,
  inputBackground: COLORS.gray800,
  inputBorder: COLORS.gray600,
  buttonPrimary: COLORS.secondary,
  buttonPrimaryText: COLORS.white,
  buttonSecondary: COLORS.primary,
  buttonSecondaryText: COLORS.white,
  buttonOutlineBorder: COLORS.secondary,
  buttonOutlineText: COLORS.secondary,
  buttonDisabled: COLORS.gray700,
  buttonDisabledText: COLORS.gray500,
  success: COLORS.success,
  error: COLORS.error,
  warning: COLORS.warning,
  info: COLORS.info,
  successBackground: '#1B5E20',
  errorBackground: '#B71C1C',
  warningBackground: '#E65100',
  infoBackground: '#0D47A1',
  overlay: COLORS.overlay,
  shimmer: COLORS.gray700,
  shimmerHighlight: COLORS.gray800,
} as const;

export type ThemeColors = typeof LIGHT_THEME_COLORS;
