export const STRINGS = {
  // ─── App Wide ────────────────────────────────────────────────────────────────
  app: {
    name: 'BBVA Mobile Banking',
    tagline: 'Banking made simple',
    loading: 'Loading…',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    apply: 'Apply',
    reset: 'Reset',
    share: 'Share',
    download: 'Download',
    copy: 'Copy',
    copiedToClipboard: 'Copied to clipboard',
    noResults: 'No results found',
    noData: 'No data available',
    errorGeneric: 'Something went wrong. Please try again.',
    errorNetwork: 'No internet connection. Please check your network settings.',
    errorTimeout: 'Request timed out. Please try again.',
    errorServer: 'Server error. Please try again later.',
    sessionExpired: 'Your session has expired. Please log in again.',
  },

  // ─── Authentication ───────────────────────────────────────────────────────────
  auth: {
    welcome: 'Welcome to BBVA',
    welcomeBack: 'Welcome back',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    changePassword: 'Change Password',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    username: 'Username',
    usernamePlaceholder: 'Enter your username',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Enter new password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    currentPassword: 'Current Password',
    currentPasswordPlaceholder: 'Enter current password',
    email: 'Email Address',
    emailPlaceholder: 'Enter your email address',
    phone: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    rememberMe: 'Remember me',
    loginWithBiometrics: 'Login with Biometrics',
    loginWithFaceId: 'Login with Face ID',
    loginWithFingerprint: 'Login with Fingerprint',
    enableBiometrics: 'Enable Biometric Login',
    biometricsNotEnrolled: 'No biometrics enrolled on this device.',
    biometricsNotSupported: 'Biometric authentication is not supported on this device.',
    biometricAuthFailed: 'Biometric authentication failed.',
    enterPin: 'Enter PIN',
    createPin: 'Create PIN',
    confirmPin: 'Confirm PIN',
    pinPlaceholder: '••••••',
    pinMismatch: 'PINs do not match. Please try again.',
    passwordMismatch: 'Passwords do not match.',
    passwordTooShort: 'Password must be at least 8 characters.',
    passwordRequirements: 'Password must contain uppercase, lowercase, number, and special character.',
    invalidCredentials: 'Invalid username or password.',
    accountLocked: 'Account locked. Please contact support.',
    tooManyAttempts: 'Too many failed attempts. Please wait and try again.',
    otpSent: 'OTP sent to your registered phone number.',
    enterOtp: 'Enter OTP',
    otpPlaceholder: 'Enter 6-digit OTP',
    otpExpired: 'OTP has expired. Please request a new one.',
    invalidOtp: 'Invalid OTP. Please try again.',
    resendOtp: 'Resend OTP',
    resendOtpIn: 'Resend OTP in {seconds}s',
    termsAndConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    agreeToTerms: 'I agree to the Terms & Conditions and Privacy Policy',
    mustAgreeToTerms: 'You must agree to the terms to continue.',
  },

  // ─── Accounts ─────────────────────────────────────────────────────────────────
  accounts: {
    title: 'Accounts',
    myAccounts: 'My Accounts',
    accountDetails: 'Account Details',
    accountNumber: 'Account Number',
    accountType: 'Account Type',
    accountName: 'Account Name',
    balance: 'Balance',
    availableBalance: 'Available Balance',
    currentBalance: 'Current Balance',
    pendingBalance: 'Pending',
    currency: 'Currency',
    iban: 'IBAN',
    swift: 'SWIFT / BIC',
    bankName: 'Bank Name',
    branchName: 'Branch',
    openDate: 'Open Date',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    blocked: 'Blocked',
    checking: 'Checking Account',
    savings: 'Savings Account',
    businessChecking: 'Business Checking',
    transactions: 'Transactions',
    recentTransactions: 'Recent Transactions',
    allTransactions: 'All Transactions',
    noTransactions: 'No transactions found.',
    transfer: 'Transfer',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    totalBalance: 'Total Balance',
    addAccount: 'Add Account',
    linkAccount: 'Link Account',
    removeAccount: 'Remove Account',
    shareAccountDetails: 'Share Account Details',
    downloadStatement: 'Download Statement',
    viewStatement: 'View Statement',
    statementPeriod: 'Statement Period',
  },

  // ─── Cards ────────────────────────────────────────────────────────────────────
  cards: {
    title: 'Cards',
    myCards: 'My Cards',
    cardDetails: 'Card Details',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cardType: 'Card Type',
    debitCard: 'Debit Card',
    creditCard: 'Credit Card',
    prepaidCard: 'Prepaid Card',
    virtualCard: 'Virtual Card',
    creditLimit: 'Credit Limit',
    availableCredit: 'Available Credit',
    usedCredit: 'Used Credit',
    minimumPayment: 'Minimum Payment',
    paymentDueDate: 'Payment Due Date',
    outstandingBalance: 'Outstanding Balance',
    cashAdvanceLimit: 'Cash Advance Limit',
    internationalTransactions: 'International Transactions',
    onlineTransactions: 'Online Transactions',
    contactlessPayments: 'Contactless Payments',
    atmWithdrawals: 'ATM Withdrawals',
    blockCard: 'Block Card',
    unblockCard: 'Unblock Card',
    reportLostStolen: 'Report Lost / Stolen',
    replaceCard: 'Replace Card',
    activateCard: 'Activate Card',
    setPin: 'Set PIN',
    changePinCard: 'Change Card PIN',
    viewCardPin: 'View PIN',
    freezeCard: 'Freeze Card',
    unfreezeCard: 'Unfreeze Card',
    manageCard: 'Manage Card',
    addCard: 'Add Card',
    spendingLimits: 'Spending Limits',
    dailyLimit: 'Daily Limit',
    monthlyLimit: 'Monthly Limit',
    perTransactionLimit: 'Per Transaction Limit',
    cardStatus: 'Card Status',
    cardActive: 'Active',
    cardFrozen: 'Frozen',
    cardBlocked: 'Blocked',
    cardExpired: 'Expired',
    rewardsPoints: 'Rewards Points',
    cashback: 'Cashback',
  },

  // ─── Credits / Loans ──────────────────────────────────────────────────────────
  credits: {
    title: 'Credits',
    myLoans: 'My Loans',
    loanDetails: 'Loan Details',
    loanType: 'Loan Type',
    personalLoan: 'Personal Loan',
    homeLoan: 'Home Loan / Mortgage',
    autoLoan: 'Auto Loan',
    businessLoan: 'Business Loan',
    studentLoan: 'Student Loan',
    lineOfCredit: 'Line of Credit',
    loanAmount: 'Loan Amount',
    disbursedAmount: 'Disbursed Amount',
    principalAmount: 'Principal Amount',
    outstandingAmount: 'Outstanding Amount',
    interestRate: 'Interest Rate',
    annualPercentageRate: 'Annual Percentage Rate (APR)',
    emi: 'EMI',
    nextEmiDate: 'Next EMI Date',
    nextEmiAmount: 'Next EMI Amount',
    totalEmi: 'Total EMI',
    emiPaid: 'EMI Paid',
    emiRemaining: 'EMI Remaining',
    tenure: 'Tenure',
    months: '{count} Months',
    years: '{count} Years',
    startDate: 'Start Date',
    endDate: 'End Date',
    maturityDate: 'Maturity Date',
    totalInterest: 'Total Interest',
    totalPayable: 'Total Payable',
    prepayment: 'Prepayment',
    partialPrepayment: 'Partial Prepayment',
    foreclosure: 'Foreclosure',
    amortizationSchedule: 'Amortization Schedule',
    paymentHistory: 'Payment History',
    applyForLoan: 'Apply for a Loan',
    loanStatus: 'Loan Status',
    active: 'Active',
    closed: 'Closed',
    overdue: 'Overdue',
    inReview: 'In Review',
    approved: 'Approved',
    rejected: 'Rejected',
    overdueAmount: 'Overdue Amount',
    overdueByDays: 'Overdue by {days} days',
  },

  // ─── Investments ──────────────────────────────────────────────────────────────
  investments: {
    title: 'Investments',
    portfolio: 'Portfolio',
    portfolioValue: 'Portfolio Value',
    totalInvested: 'Total Invested',
    totalReturns: 'Total Returns',
    totalReturnsPercent: 'Returns (%)',
    todaysGain: "Today's Gain",
    overallGain: 'Overall Gain',
    mutualFunds: 'Mutual Funds',
    stocks: 'Stocks',
    bonds: 'Bonds',
    fixedDeposits: 'Fixed Deposits',
    recurringDeposits: 'Recurring Deposits',
    etf: 'ETF',
    gold: 'Digital Gold',
    realEstate: 'Real Estate Fund',
    fundName: 'Fund Name',
    nav: 'NAV',
    units: 'Units',
    currentValue: 'Current Value',
    investedValue: 'Invested Value',
    xirr: 'XIRR',
    absoluteReturn: 'Absolute Return',
    buyPrice: 'Buy Price',
    currentPrice: 'Current Price',
    quantity: 'Quantity',
    sector: 'Sector',
    riskLevel: 'Risk Level',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    horizon: 'Investment Horizon',
    shortTerm: 'Short Term',
    mediumTerm: 'Medium Term',
    longTerm: 'Long Term',
    invest: 'Invest',
    redeem: 'Redeem',
    sipAmount: 'SIP Amount',
    sipDate: 'SIP Date',
    createSip: 'Create SIP',
    modifySip: 'Modify SIP',
    cancelSip: 'Cancel SIP',
    marketOverview: 'Market Overview',
    watchlist: 'Watchlist',
    addToWatchlist: 'Add to Watchlist',
    removeFromWatchlist: 'Remove from Watchlist',
    performance: 'Performance',
    oneDay: '1D',
    oneWeek: '1W',
    oneMonth: '1M',
    threeMonths: '3M',
    sixMonths: '6M',
    oneYear: '1Y',
    threeYears: '3Y',
    fiveYears: '5Y',
    allTime: 'All',
  },

  // ─── Profile & Settings ───────────────────────────────────────────────────────
  profile: {
    title: 'Profile',
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    nationality: 'Nationality',
    idType: 'ID Type',
    idNumber: 'ID Number',
    taxId: 'Tax ID / TIN',
    contactInfo: 'Contact Information',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    alternatePhone: 'Alternate Phone',
    address: 'Address',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2',
    city: 'City',
    state: 'State / Province',
    postalCode: 'Postal Code',
    country: 'Country',
    settings: 'Settings',
    notifications: 'Notifications',
    notificationPreferences: 'Notification Preferences',
    pushNotifications: 'Push Notifications',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    transactionAlerts: 'Transaction Alerts',
    securityAlerts: 'Security Alerts',
    promotionalOffers: 'Promotional Offers',
    language: 'Language',
    selectLanguage: 'Select Language',
    currency: 'Currency',
    theme: 'Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    systemDefault: 'System Default',
    biometricLogin: 'Biometric Login',
    twoFactorAuth: 'Two-Factor Authentication',
    loginActivity: 'Login Activity',
    deviceManagement: 'Device Management',
    linkedDevices: 'Linked Devices',
    removeDevice: 'Remove Device',
    helpSupport: 'Help & Support',
    faq: 'FAQ',
    contactUs: 'Contact Us',
    liveChat: 'Live Chat',
    callUs: 'Call Us',
    reportIssue: 'Report an Issue',
    feedback: 'Feedback',
    about: 'About',
    version: 'Version',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    licenses: 'Open Source Licenses',
    logout: 'Log Out',
    logoutConfirm: 'Are you sure you want to log out?',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action is permanent and cannot be undone.',
    editProfile: 'Edit Profile',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully.',
    changeProfilePhoto: 'Change Profile Photo',
    removeProfilePhoto: 'Remove Profile Photo',
    takePhoto: 'Take Photo',
    chooseFromLibrary: 'Choose from Library',
  },

  // ─── Transfers ────────────────────────────────────────────────────────────────
  transfers: {
    title: 'Transfer',
    newTransfer: 'New Transfer',
    transferHistory: 'Transfer History',
    sendMoney: 'Send Money',
    requestMoney: 'Request Money',
    fromAccount: 'From Account',
    toAccount: 'To Account',
    recipient: 'Recipient',
    recipientName: 'Recipient Name',
    recipientAccount: 'Recipient Account',
    recipientBank: 'Recipient Bank',
    amount: 'Amount',
    currency: 'Currency',
    note: 'Note / Reference',
    notePlaceholder: 'Add a note (optional)',
    transferType: 'Transfer Type',
    ownAccount: 'Own Account',
    domestic: 'Domestic',
    international: 'International',
    scheduled: 'Scheduled',
    recurring: 'Recurring',
    frequency: 'Frequency',
    once: 'Once',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    transferDate: 'Transfer Date',
    fees: 'Transaction Fee',
    exchangeRate: 'Exchange Rate',
    estimatedArrival: 'Estimated Arrival',
    confirmTransfer: 'Confirm Transfer',
    transferSuccess: 'Transfer Successful',
    transferFailed: 'Transfer Failed',
    insufficientFunds: 'Insufficient funds.',
    dailyLimitExceeded: 'Daily transfer limit exceeded.',
    savedBeneficiaries: 'Saved Beneficiaries',
    addBeneficiary: 'Add Beneficiary',
    recentRecipients: 'Recent Recipients',
    scanQrCode: 'Scan QR Code',
    referenceNumber: 'Reference Number',
  },

  // ─── Notifications ────────────────────────────────────────────────────────────
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark All as Read',
    noNotifications: 'No notifications yet.',
    today: 'Today',
    yesterday: 'Yesterday',
    earlier: 'Earlier',
  },
} as const;

export type StringsKey = keyof typeof STRINGS;
