export const STRINGS = {
  // ─── App Wide ────────────────────────────────────────────────────────────────
  app: {
    name: 'BBVA Mobile Banking',
    tagline: 'La banca, más simple',
    loading: 'Cargando…',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Guardar',
    close: 'Cerrar',
    back: 'Volver',
    next: 'Siguiente',
    done: 'Listo',
    ok: 'OK',
    yes: 'Sí',
    no: 'No',
    edit: 'Editar',
    delete: 'Eliminar',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    apply: 'Aplicar',
    reset: 'Restablecer',
    share: 'Compartir',
    download: 'Descargar',
    copy: 'Copiar',
    copiedToClipboard: 'Copiado al portapapeles',
    noResults: 'No se encontraron resultados',
    noData: 'No hay datos disponibles',
    errorGeneric: 'Se ha producido un error. Inténtelo de nuevo.',
    errorNetwork: 'No hay conexión a internet. Revise la configuración de su red.',
    errorTimeout: 'La solicitud ha caducado. Inténtelo de nuevo.',
    errorServer: 'Error del servidor. Inténtelo más tarde.',
    sessionExpired: 'Su sesión ha expirado. Inicie sesión de nuevo.',
  },

  // ─── Authentication ───────────────────────────────────────────────────────────
  auth: {
    welcome: 'Bienvenido a BBVA',
    welcomeBack: 'Bienvenido de nuevo',
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    signUp: 'Registrarse',
    forgotPassword: '¿Olvidó su contraseña?',
    resetPassword: 'Restablecer contraseña',
    changePassword: 'Cambiar contraseña',
    createAccount: 'Crear cuenta',
    alreadyHaveAccount: '¿Ya tiene una cuenta?',
    dontHaveAccount: '¿No tiene una cuenta?',
    username: 'Usuario',
    usernamePlaceholder: 'Introduzca su usuario',
    password: 'Contraseña',
    passwordPlaceholder: 'Introduzca su contraseña',
    newPassword: 'Nueva contraseña',
    newPasswordPlaceholder: 'Introduzca la nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    confirmPasswordPlaceholder: 'Confirme su contraseña',
    currentPassword: 'Contraseña actual',
    currentPasswordPlaceholder: 'Introduzca la contraseña actual',
    email: 'Correo electrónico',
    emailPlaceholder: 'Introduzca su correo electrónico',
    phone: 'Número de teléfono',
    phonePlaceholder: 'Introduzca su número de teléfono',
    rememberMe: 'Recordarme',
    loginWithBiometrics: 'Acceder con biometría',
    loginWithFaceId: 'Acceder con Face ID',
    loginWithFingerprint: 'Acceder con huella dactilar',
    enableBiometrics: 'Activar acceso biométrico',
    biometricsNotEnrolled: 'No hay datos biométricos registrados en este dispositivo.',
    biometricsNotSupported: 'La autenticación biométrica no es compatible con este dispositivo.',
    biometricAuthFailed: 'La autenticación biométrica ha fallado.',
    enterPin: 'Introduzca el PIN',
    createPin: 'Crear PIN',
    confirmPin: 'Confirmar PIN',
    pinPlaceholder: '••••••',
    pinMismatch: 'Los PIN no coinciden. Inténtelo de nuevo.',
    passwordMismatch: 'Las contraseñas no coinciden.',
    passwordTooShort: 'La contraseña debe tener al menos 8 caracteres.',
    passwordRequirements: 'La contraseña debe contener mayúsculas, minúsculas, números y un carácter especial.',
    invalidCredentials: 'Usuario o contraseña no válidos.',
    accountLocked: 'Cuenta bloqueada. Contacte con el soporte.',
    tooManyAttempts: 'Demasiados intentos fallidos. Espere antes de volver a intentarlo.',
    otpSent: 'El código OTP se ha enviado a su número de teléfono registrado.',
    enterOtp: 'Introduzca el OTP',
    otpPlaceholder: 'Introduzca el OTP de 6 dígitos',
    otpExpired: 'El OTP ha expirado. Solicite uno nuevo.',
    invalidOtp: 'OTP no válido. Inténtelo de nuevo.',
    resendOtp: 'Reenviar OTP',
    resendOtpIn: 'Reenviar OTP en {seconds}s',
    termsAndConditions: 'Términos y condiciones',
    privacyPolicy: 'Política de privacidad',
    agreeToTerms: 'Acepto los Términos y condiciones y la Política de privacidad',
    mustAgreeToTerms: 'Debe aceptar los términos para continuar.',
  },

  // ─── Accounts ─────────────────────────────────────────────────────────────────
  accounts: {
    title: 'Cuentas',
    myAccounts: 'Mis Cuentas',
    accountDetails: 'Detalles de la cuenta',
    accountNumber: 'Número de cuenta',
    accountType: 'Tipo de cuenta',
    accountName: 'Nombre de la cuenta',
    balance: 'Saldo',
    availableBalance: 'Saldo disponible',
    currentBalance: 'Saldo actual',
    pendingBalance: 'Pendiente',
    currency: 'Divisa',
    iban: 'IBAN',
    swift: 'SWIFT / BIC',
    bankName: 'Nombre del banco',
    branchName: 'Sucursal',
    openDate: 'Fecha de apertura',
    status: 'Estado',
    active: 'Activa',
    inactive: 'Inactiva',
    blocked: 'Bloqueada',
    checking: 'Cuenta corriente',
    savings: 'Cuenta de ahorro',
    businessChecking: 'Cuenta corriente empresa',
    transactions: 'Transacciones',
    recentTransactions: 'Transacciones recientes',
    allTransactions: 'Todas las transacciones',
    noTransactions: 'No se encontraron transacciones.',
    transfer: 'Transferencia',
    deposit: 'Ingreso',
    withdraw: 'Retirada',
    totalBalance: 'Saldo total',
    addAccount: 'Añadir cuenta',
    linkAccount: 'Vincular cuenta',
    removeAccount: 'Eliminar cuenta',
    shareAccountDetails: 'Compartir datos de la cuenta',
    downloadStatement: 'Descargar extracto',
    viewStatement: 'Ver extracto',
    statementPeriod: 'Periodo del extracto',
  },

  // ─── Cards ────────────────────────────────────────────────────────────────────
  cards: {
    title: 'Tarjetas',
    myCards: 'Mis Tarjetas',
    cardDetails: 'Detalles de la tarjeta',
    cardNumber: 'Número de tarjeta',
    cardHolder: 'Titular',
    expiryDate: 'Fecha de vencimiento',
    cvv: 'CVV',
    cardType: 'Tipo de tarjeta',
    debitCard: 'Tarjeta de débito',
    creditCard: 'Tarjeta de crédito',
    prepaidCard: 'Tarjeta prepago',
    virtualCard: 'Tarjeta virtual',
    creditLimit: 'Límite de crédito',
    availableCredit: 'Crédito disponible',
    usedCredit: 'Crédito utilizado',
    minimumPayment: 'Pago mínimo',
    paymentDueDate: 'Fecha límite de pago',
    outstandingBalance: 'Saldo pendiente',
    cashAdvanceLimit: 'Límite de disposición de efectivo',
    internationalTransactions: 'Transacciones internacionales',
    onlineTransactions: 'Transacciones en línea',
    contactlessPayments: 'Pagos sin contacto',
    atmWithdrawals: 'Retiradas en cajero',
    blockCard: 'Bloquear tarjeta',
    unblockCard: 'Desbloquear tarjeta',
    reportLostStolen: 'Reportar pérdida / robo',
    replaceCard: 'Sustituir tarjeta',
    activateCard: 'Activar tarjeta',
    setPin: 'Configurar PIN',
    changePinCard: 'Cambiar PIN de la tarjeta',
    viewCardPin: 'Ver PIN',
    freezeCard: 'Congelar tarjeta',
    unfreezeCard: 'Descongelar tarjeta',
    manageCard: 'Gestionar tarjeta',
    addCard: 'Añadir tarjeta',
    spendingLimits: 'Límites de gasto',
    dailyLimit: 'Límite diario',
    monthlyLimit: 'Límite mensual',
    perTransactionLimit: 'Límite por transacción',
    cardStatus: 'Estado de la tarjeta',
    cardActive: 'Activa',
    cardFrozen: 'Congelada',
    cardBlocked: 'Bloqueada',
    cardExpired: 'Vencida',
    rewardsPoints: 'Puntos de recompensa',
    cashback: 'Cashback',
  },

  // ─── Credits / Loans ──────────────────────────────────────────────────────────
  credits: {
    title: 'Créditos',
    myLoans: 'Mis préstamos',
    loanDetails: 'Detalles del préstamo',
    loanType: 'Tipo de préstamo',
    personalLoan: 'Préstamo personal',
    homeLoan: 'Hipoteca',
    autoLoan: 'Préstamo para vehículo',
    businessLoan: 'Préstamo empresarial',
    studentLoan: 'Préstamo estudiantil',
    lineOfCredit: 'Línea de crédito',
    loanAmount: 'Importe del préstamo',
    disbursedAmount: 'Importe desembolsado',
    principalAmount: 'Capital principal',
    outstandingAmount: 'Importe pendiente',
    interestRate: 'Tipo de interés',
    annualPercentageRate: 'Tasa anual equivalente (TAE)',
    emi: 'EMI',
    nextEmiDate: 'Fecha de la próxima cuota',
    nextEmiAmount: 'Importe de la próxima cuota',
    totalEmi: 'Total de cuotas',
    emiPaid: 'Cuotas pagadas',
    emiRemaining: 'Cuotas restantes',
    tenure: 'Plazo',
    months: '{count} meses',
    years: '{count} años',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    maturityDate: 'Fecha de vencimiento',
    totalInterest: 'Intereses totales',
    totalPayable: 'Total a pagar',
    prepayment: 'Amortización anticipada',
    partialPrepayment: 'Amortización parcial',
    foreclosure: 'Cancelación anticipada',
    amortizationSchedule: 'Cuadro de amortización',
    paymentHistory: 'Historial de pagos',
    applyForLoan: 'Solicitar un préstamo',
    loanStatus: 'Estado del préstamo',
    active: 'Activo',
    closed: 'Cerrado',
    overdue: 'Vencido',
    inReview: 'En revisión',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    overdueAmount: 'Importe vencido',
    overdueByDays: 'Vencido hace {days} días',
  },

  // ─── Investments ──────────────────────────────────────────────────────────────
  investments: {
    title: 'Inversiones',
    portfolio: 'Cartera',
    portfolioValue: 'Valor de la cartera',
    totalInvested: 'Total invertido',
    totalReturns: 'Rendimiento total',
    totalReturnsPercent: 'Rendimiento (%)',
    todaysGain: 'Ganancia de hoy',
    overallGain: 'Ganancia global',
    mutualFunds: 'Fondos de inversión',
    stocks: 'Acciones',
    bonds: 'Bonos',
    fixedDeposits: 'Depósitos a plazo',
    recurringDeposits: 'Depósitos recurrentes',
    etf: 'ETF',
    gold: 'Oro digital',
    realEstate: 'Fondo inmobiliario',
    fundName: 'Nombre del fondo',
    nav: 'NAV',
    units: 'Unidades',
    currentValue: 'Valor actual',
    investedValue: 'Valor invertido',
    xirr: 'XIRR',
    absoluteReturn: 'Rentabilidad absoluta',
    buyPrice: 'Precio de compra',
    currentPrice: 'Precio actual',
    quantity: 'Cantidad',
    sector: 'Sector',
    riskLevel: 'Nivel de riesgo',
    low: 'Bajo',
    moderate: 'Moderado',
    high: 'Alto',
    horizon: 'Horizonte de inversión',
    shortTerm: 'Corto plazo',
    mediumTerm: 'Medio plazo',
    longTerm: 'Largo plazo',
    invest: 'Invertir',
    redeem: 'Reembolsar',
    sipAmount: 'Importe del SIP',
    sipDate: 'SIP Date',
    createSip: 'Crear SIP',
    modifySip: 'Modificar SIP',
    cancelSip: 'Cancelar SIP',
    marketOverview: 'Resumen del mercado',
    watchlist: 'Lista de seguimiento',
    addToWatchlist: 'Añadir a la lista de seguimiento',
    removeFromWatchlist: 'Quitar de la lista de seguimiento',
    performance: 'Rentabilidad',
    oneDay: '1D',
    oneWeek: '1W',
    oneMonth: '1M',
    threeMonths: '3M',
    sixMonths: '6M',
    oneYear: '1Y',
    threeYears: '3Y',
    fiveYears: '5Y',
    allTime: 'All',
  },

  // ─── Profile & Settings ───────────────────────────────────────────────────────
  profile: {
    title: 'Perfil',
    myProfile: 'Mi Perfil',
    personalInfo: 'Información personal',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    fullName: 'Nombre completo',
    dateOfBirth: 'Fecha de nacimiento',
    gender: 'Género',
    nationality: 'Nacionalidad',
    idType: 'Tipo de documento',
    idNumber: 'Número de documento',
    taxId: 'NIF / TIN',
    contactInfo: 'Información de contacto',
    emailAddress: 'Correo electrónico',
    phoneNumber: 'Número de teléfono',
    alternatePhone: 'Teléfono alternativo',
    address: 'Dirección',
    addressLine1: 'Dirección, línea 1',
    addressLine2: 'Dirección, línea 2',
    city: 'Ciudad',
    state: 'Provincia / Estado',
    postalCode: 'Código postal',
    country: 'País',
    settings: 'Configuración',
    notifications: 'Notificaciones',
    notificationPreferences: 'Preferencias de notificación',
    pushNotifications: 'Notificaciones push',
    emailNotifications: 'Notificaciones por correo',
    smsNotifications: 'Notificaciones por SMS',
    transactionAlerts: 'Alertas de transacciones',
    securityAlerts: 'Alertas de seguridad',
    promotionalOffers: 'Ofertas promocionales',
    language: 'Idioma',
    selectLanguage: 'Seleccionar idioma',
    currency: 'Divisa',
    theme: 'Tema',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    systemDefault: 'Predeterminado del sistema',
    biometricLogin: 'Acceso biométrico',
    twoFactorAuth: 'Autenticación en dos pasos',
    loginActivity: 'Actividad de acceso',
    deviceManagement: 'Gestión de dispositivos',
    linkedDevices: 'Dispositivos vinculados',
    removeDevice: 'Eliminar dispositivo',
    helpSupport: 'Ayuda y soporte',
    faq: 'FAQ',
    contactUs: 'Contáctenos',
    liveChat: 'Chat en directo',
    callUs: 'Llámenos',
    reportIssue: 'Reportar un problema',
    feedback: 'Comentarios',
    about: 'Acerca de',
    version: 'Versión',
    termsOfService: 'Términos del servicio',
    privacyPolicy: 'Política de privacidad',
    licenses: 'Licencias de código abierto',
    logout: 'Cerrar sesión',
    logoutConfirm: '¿Está seguro de que desea cerrar sesión?',
    deleteAccount: 'Eliminar cuenta',
    deleteAccountWarning: 'Esta acción es permanente y no se puede deshacer.',
    editProfile: 'Editar perfil',
    updateProfile: 'Actualizar perfil',
    profileUpdated: 'Perfil actualizado correctamente.',
    changeProfilePhoto: 'Cambiar foto de perfil',
    removeProfilePhoto: 'Eliminar foto de perfil',
    takePhoto: 'Tomar foto',
    chooseFromLibrary: 'Elegir de la biblioteca',
  },

  // ─── Transfers ────────────────────────────────────────────────────────────────
  transfers: {
    title: 'Transferencia',
    newTransfer: 'Nueva transferencia',
    transferHistory: 'Historial de transferencias',
    sendMoney: 'Enviar dinero',
    requestMoney: 'Solicitar dinero',
    fromAccount: 'Desde la cuenta',
    toAccount: 'Hacia la cuenta',
    recipient: 'Destinatario',
    recipientName: 'Nombre del destinatario',
    recipientAccount: 'Cuenta del destinatario',
    recipientBank: 'Banco del destinatario',
    amount: 'Importe',
    currency: 'Divisa',
    note: 'Nota / Referencia',
    notePlaceholder: 'Añada una nota (opcional)',
    transferType: 'Tipo de transferencia',
    ownAccount: 'Cuenta propia',
    domestic: 'Nacional',
    international: 'Internacional',
    scheduled: 'Programada',
    recurring: 'Recurrente',
    frequency: 'Frecuencia',
    once: 'Una vez',
    daily: 'Diaria',
    weekly: 'Semanal',
    monthly: 'Mensual',
    transferDate: 'Fecha de transferencia',
    fees: 'Comisión de transacción',
    exchangeRate: 'Tipo de cambio',
    estimatedArrival: 'Llegada estimada',
    confirmTransfer: 'Confirmar transferencia',
    transferSuccess: 'Transferencia realizada correctamente',
    transferFailed: 'La transferencia ha fallado',
    insufficientFunds: 'Fondos insuficientes.',
    dailyLimitExceeded: 'Se ha superado el límite diario de transferencias.',
    savedBeneficiaries: 'Beneficiarios guardados',
    addBeneficiary: 'Añadir beneficiario',
    recentRecipients: 'Destinatarios recientes',
    scanQrCode: 'Escanear código QR',
    referenceNumber: 'Número de referencia',
  },

  // ─── Notifications ────────────────────────────────────────────────────────────
  notifications: {
    title: 'Notificaciones',
    markAllRead: 'Marcar todo como leído',
    noNotifications: 'Todavía no hay notificaciones.',
    today: 'Hoy',
    yesterday: 'Ayer',
    earlier: 'Anteriormente',
  },
} as const;

export type StringsKey = keyof typeof STRINGS;
