import type { Account, Transaction } from '../../types';

const delay = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

// ── Mock accounts ────────────────────────────────────────────────────────────

const MOCK_ACCOUNTS: Account[] = [
  {
    id: 'acc-001',
    accountNumber: '00012345678',
    iban: 'FR76 3000 6000 0112 3456 7800 189',
    type: 'checking',
    name: 'Compte Courant BBVA',
    balance: 4_287.53,
    availableBalance: 4_187.53,
    currency: 'EUR',
    isDefault: true,
    isActive: true,
    createdAt: '2019-03-15T09:00:00.000Z',
  },
  {
    id: 'acc-002',
    accountNumber: '00098765432',
    iban: 'FR76 3000 6000 0198 7654 3200 145',
    type: 'savings',
    name: 'Livret A BBVA',
    balance: 15_000.00,
    availableBalance: 15_000.00,
    currency: 'EUR',
    interestRate: 3.0,
    isDefault: false,
    isActive: true,
    createdAt: '2020-06-01T10:00:00.000Z',
  },
  {
    id: 'acc-003',
    accountNumber: '00055566677',
    iban: 'FR76 3000 6000 0155 5666 7700 201',
    type: 'savings',
    name: "Plan d'Épargne Logement",
    balance: 22_450.80,
    availableBalance: 22_450.80,
    currency: 'EUR',
    interestRate: 2.25,
    isDefault: false,
    isActive: true,
    createdAt: '2021-01-10T08:30:00.000Z',
  },
  {
    id: 'acc-004',
    accountNumber: '00077788899',
    iban: 'FR76 3000 6000 0177 7888 9900 312',
    type: 'investment',
    name: 'PEA BBVA',
    balance: 38_742.15,
    availableBalance: 38_742.15,
    currency: 'EUR',
    isDefault: false,
    isActive: true,
    createdAt: '2020-09-22T14:00:00.000Z',
  },
];

// ── Mock transactions ────────────────────────────────────────────────────────

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-001',
    accountId: 'acc-001',
    type: 'debit',
    status: 'completed',
    amount: -89.90,
    currency: 'EUR',
    description: 'CARREFOUR MARKET PARIS 11',
    category: 'groceries',
    merchant: 'Carrefour Market',
    reference: 'REF20240115001',
    date: daysAgo(1),
    balance: 4_287.53,
    notes: '',
  },
  {
    id: 'txn-002',
    accountId: 'acc-001',
    type: 'credit',
    status: 'completed',
    amount: 2_800.00,
    currency: 'EUR',
    description: 'VIREMENT SALAIRE TECH CORP',
    category: 'income',
    reference: 'SAL20240115',
    date: daysAgo(2),
    balance: 4_377.43,
    counterpartName: 'Tech Corp SAS',
    counterpartIban: 'FR76 1820 6004 3521 4567 8900 023',
  },
  {
    id: 'txn-003',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -12.99,
    currency: 'EUR',
    description: 'NETFLIX ABONNEMENT MENSUEL',
    category: 'entertainment',
    merchant: 'Netflix',
    reference: 'NF20240114',
    date: daysAgo(2),
    balance: 1_577.43,
  },
  {
    id: 'txn-004',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -54.20,
    currency: 'EUR',
    description: 'TOTAL ENERGIES STATION',
    category: 'transport',
    merchant: 'TotalEnergies',
    reference: 'TOT20240113',
    date: daysAgo(3),
    balance: 1_590.42,
  },
  {
    id: 'txn-005',
    accountId: 'acc-001',
    type: 'debit',
    status: 'completed',
    amount: -127.50,
    currency: 'EUR',
    description: 'EDF ELECTRICITE MENSUEL',
    category: 'utilities',
    merchant: 'EDF',
    reference: 'EDF20240112',
    date: daysAgo(4),
    balance: 1_644.62,
  },
  {
    id: 'txn-006',
    accountId: 'acc-001',
    type: 'transfer',
    status: 'completed',
    amount: -500.00,
    currency: 'EUR',
    description: 'VIREMENT VERS LIVRET A',
    category: 'transfer',
    reference: 'VIR20240111',
    date: daysAgo(5),
    balance: 1_772.12,
    counterpartName: 'Livret A BBVA',
    counterpartIban: 'FR76 3000 6000 0198 7654 3200 145',
  },
  {
    id: 'txn-007',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -8.90,
    currency: 'EUR',
    description: 'BOULANGERIE POILANE PARIS',
    category: 'food',
    merchant: 'Boulangerie Poilâne',
    reference: 'POI20240110',
    date: daysAgo(6),
    balance: 2_272.12,
  },
  {
    id: 'txn-008',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -65.00,
    currency: 'EUR',
    description: 'PHARMACIE CENTRALE PARIS 9',
    category: 'health',
    merchant: 'Pharmacie Centrale',
    reference: 'PHR20240109',
    date: daysAgo(7),
    balance: 2_281.02,
  },
  {
    id: 'txn-009',
    accountId: 'acc-001',
    type: 'debit',
    status: 'completed',
    amount: -34.90,
    currency: 'EUR',
    description: 'SPOTIFY PREMIUM FAMILLE',
    category: 'entertainment',
    merchant: 'Spotify',
    reference: 'SPO20240108',
    date: daysAgo(8),
    balance: 2_346.02,
  },
  {
    id: 'txn-010',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -145.00,
    currency: 'EUR',
    description: 'SNCF BILLET PARIS-LYON',
    category: 'transport',
    merchant: 'SNCF',
    reference: 'SNC20240107',
    date: daysAgo(9),
    balance: 2_380.92,
  },
  {
    id: 'txn-011',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -22.80,
    currency: 'EUR',
    description: 'MONOPRIX COURS DE VINCENNES',
    category: 'groceries',
    merchant: 'Monoprix',
    reference: 'MON20240107',
    date: daysAgo(9),
    balance: 2_525.92,
  },
  {
    id: 'txn-012',
    accountId: 'acc-001',
    type: 'debit',
    status: 'completed',
    amount: -800.00,
    currency: 'EUR',
    description: 'LOYER DECEMBRE IMMOBILIER',
    category: 'housing',
    reference: 'LOY20240106',
    date: daysAgo(10),
    balance: 2_548.72,
  },
  {
    id: 'txn-013',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -47.60,
    currency: 'EUR',
    description: 'RESTAURANT LE COMPTOIR',
    category: 'food',
    merchant: 'Le Comptoir du Relais',
    reference: 'RES20240105',
    date: daysAgo(11),
    balance: 3_348.72,
  },
  {
    id: 'txn-014',
    accountId: 'acc-001',
    type: 'credit',
    status: 'completed',
    amount: 250.00,
    currency: 'EUR',
    description: 'REMBOURSEMENT ASSURANCE MAIF',
    category: 'insurance',
    merchant: 'MAIF',
    reference: 'MAI20240104',
    date: daysAgo(12),
    balance: 3_396.32,
  },
  {
    id: 'txn-015',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -189.00,
    currency: 'EUR',
    description: 'FNAC PARIS REPUBLIQUE',
    category: 'shopping',
    merchant: 'FNAC',
    reference: 'FNA20240103',
    date: daysAgo(13),
    balance: 3_146.32,
  },
  {
    id: 'txn-016',
    accountId: 'acc-001',
    type: 'payment',
    status: 'pending',
    amount: -35.00,
    currency: 'EUR',
    description: 'AMAZON.FR COMMANDE',
    category: 'shopping',
    merchant: 'Amazon',
    reference: 'AMZ20240102',
    date: daysAgo(1),
    balance: 3_335.32,
  },
  {
    id: 'txn-017',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -9.99,
    currency: 'EUR',
    description: 'APPLE ICLOUD STOCKAGE',
    category: 'technology',
    merchant: 'Apple',
    reference: 'APL20240101',
    date: daysAgo(14),
    balance: 3_370.32,
  },
  {
    id: 'txn-018',
    accountId: 'acc-001',
    type: 'transfer',
    status: 'completed',
    amount: -200.00,
    currency: 'EUR',
    description: 'VIREMENT MARIE DUPONT',
    category: 'transfer',
    reference: 'VIR20231230',
    date: daysAgo(15),
    balance: 3_380.31,
    counterpartName: 'Marie Dupont',
    counterpartIban: 'FR76 2004 1010 0505 0013 0080 439',
  },
  {
    id: 'txn-019',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -78.50,
    currency: 'EUR',
    description: 'ORANGE MOBILE FACTURE',
    category: 'utilities',
    merchant: 'Orange',
    reference: 'ORA20231229',
    date: daysAgo(16),
    balance: 3_580.31,
  },
  {
    id: 'txn-020',
    accountId: 'acc-001',
    type: 'debit',
    status: 'completed',
    amount: -1_250.00,
    currency: 'EUR',
    description: 'REMBOURSEMENT CREDIT PERSONNEL',
    category: 'finance',
    reference: 'CRD20231228',
    date: daysAgo(17),
    balance: 3_658.81,
  },
  {
    id: 'txn-021',
    accountId: 'acc-001',
    type: 'credit',
    status: 'completed',
    amount: 150.00,
    currency: 'EUR',
    description: 'CASHBACK CARTE BBVA PREMIUM',
    category: 'income',
    reference: 'CSH20231227',
    date: daysAgo(18),
    balance: 4_908.81,
  },
  {
    id: 'txn-022',
    accountId: 'acc-001',
    type: 'payment',
    status: 'completed',
    amount: -42.00,
    currency: 'EUR',
    description: 'UBER COURSE TAXI',
    category: 'transport',
    merchant: 'Uber',
    reference: 'UBR20231226',
    date: daysAgo(19),
    balance: 4_758.81,
  },
  {
    id: 'txn-023',
    accountId: 'acc-001',
    type: 'payment',
    status: 'failed',
    amount: -500.00,
    currency: 'EUR',
    description: 'VIREMENT ANNULE PROVISION',
    category: 'transfer',
    reference: 'VIR20231225',
    date: daysAgo(20),
    balance: 4_800.81,
  },
];

// ── API functions ────────────────────────────────────────────────────────────

export const fetchAccountsApi = async (): Promise<Account[]> => {
  await delay(700);
  return [...MOCK_ACCOUNTS];
};

export const fetchTransactionsApi = async (
  accountId: string,
  page = 1,
  pageSize = 20,
): Promise<{ transactions: Transaction[]; hasMore: boolean; total: number }> => {
  await delay(600);
  const filtered = MOCK_TRANSACTIONS.filter((t) => t.accountId === accountId);
  const start = (page - 1) * pageSize;
  const slice = filtered.slice(start, start + pageSize);
  return {
    transactions: slice,
    hasMore: start + pageSize < filtered.length,
    total: filtered.length,
  };
};

export const fetchAccountDetailsApi = async (accountId: string): Promise<Account> => {
  await delay(500);
  const account = MOCK_ACCOUNTS.find((a) => a.id === accountId);
  if (!account) throw new Error(`Compte introuvable : ${accountId}`);
  return { ...account };
};
